<?php

/**
 * @file
 * Module file.
 */

/**
 * Implements hook_menu().
 */
function islandora_onthisday_menu() {
  $items = array();
  $items['admin/islandora/tools/onthisday'] = array(
    'title' => 'Islandora On This Day',
    'description' => 'Configure the Islandora On This Day module.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('islandora_onthisday_admin_settings'),
    'access arguments' => array('administer site configuration'),
    'type' => MENU_NORMAL_ITEM,
  );
  $items['onthisday'] = array(
    'title' => 'On This Day',
    'page callback' => 'islandora_onthisday_gallery',
    'access arguments' => array(ISLANDORA_VIEW_OBJECTS),
    'type' => MENU_CALLBACK,
  );
  $items['onthisday/rss'] = array(
    'page callback' => 'islandora_onthisday_rss_channel',
    'delivery callback' => 'islandora_onthisday_rss_output',
    'access arguments' => array(ISLANDORA_VIEW_OBJECTS),
    'type' => MENU_CALLBACK,
  );
  return $items;
}

/**
 * Admin settings form builder.
 */
function islandora_onthisday_admin_settings() {
  $form['islandora_onthisday_date_fields'] = array(
    '#title' => t('Date fields in Solr to query and retrieve'),
    '#type' => 'textfield',
    '#size' => 160,
    '#default_value' => variable_get('islandora_onthisday_date_fields', 'mods_originInfo_dateIssued_ms, mods_originInfo_dateCreated_ms'),
    '#description' => t("Comma-separated list of Solr field names to query for dates (and to retrieve in results to get the object's year). Date values are assumed to be in YYYY-MM-DD format. For best results, uses fields that are multivalued and that are tokenized."),
    '#maxlength' => 255,
  );
  $form['islandora_onthisday_sort_field'] = array(
    '#title' => t('Date field to sort on'),
    '#type' => 'textfield',
    '#size' => 160,
    '#default_value' => variable_get('islandora_onthisday_sort_field', ''),
    '#description' => t('The Solr field to sort results on, followed by " asc" or " desc" (for example, "mods_originInfo_dateIssued_dt asc"). You must use a field that is not multivalued. Leave blank to bypass Solr sorting and sort on the year value parsed out from the metadata.'),
    '#maxlength' => 255,
  );
  $form['islandora_onthisday_show_collections'] = array(
    '#type' => 'checkbox',
    '#title' => t('Display collection links'),
    '#default_value' => variable_get('islandora_onthisday_show_collections', 0),
    '#description' => t('Display links to collections object is in.'),
  );
  $form['islandora_onthisday_cache_data'] = array(
    '#type' => 'checkbox',
    '#title' => t('Cache list of daily objects'),
    '#default_value' => variable_get('islandora_onthisday_cache_data', 0),
    '#description' => t('May improve performance on large or busy sites. Old daily caches are cleared by Drupal cron.'),
  );
  $form['islandora_onthisday_set_limit'] = array(
    '#type' => 'checkbox',
    '#title' => t('Limit number of objects in gallery'),
    '#default_value' => variable_get('islandora_onthisday_set_limit', 0),
    '#description' => t('Limit the number of objects in the "On this day" gallery.'),
  );
  $form['islandora_onthisday_max_objects'] = array(
    '#title' => t('Maximum number of objects to show'),
    '#type' => 'textfield',
    '#size' => 10,
    '#default_value' => variable_get('islandora_onthisday_max_objects', '50'),
    '#maxlength' => 5,
    '#description' => t('Objects shown will be a randomly selected subset of all matching objects.'),
    '#states' => array(
      'visible' => array(
        ':input[name="islandora_onthisday_set_limit"]' => array('checked' => TRUE),
      ),
    ),
  );
  $form['islandora_onthisday_test_dates_enable'] = array(
    '#type' => 'checkbox',
    '#title' => t('Enable adding test date in URL, e.g., /onthisday/02-26.'),
    '#default_value' => variable_get('islandora_onthisday_test_dates_enable', 0),
    '#description' => t('For testing purposes only; disable in production. Test date must be in mm-dd format. Does not work if caching is enabled.'),
  );
  $form['islandora_onthisday_show_debugging_metadata'] = array(
    '#type' => 'checkbox',
    '#title' => t('Display debugging metadata'),
    '#default_value' => variable_get('islandora_onthisday_show_debugging_metadata', 0),
    '#description' => t('Display values of metadata fields configured above to admin users for debugging purposes.'),
  );
  return system_settings_form($form);
}

/**
 * Implements hook_theme().
 */
function islandora_onthisday_theme() {
  return array(
    'islandora_onthisday_gallery' => array(
      'template' => 'theme/islandora-onthisday-gallery',
      'file' => 'theme/theme.inc',
      'variables' => array('islandora_objects' => NULL),
    ),
    'islandora_onthisday_object' => array(
      'template' => 'theme/islandora-onthisday-object',
      'file' => 'theme/theme.inc',
      'variables' => array('islandora_object' => NULL),
    ),
    'islandora_onthisday_rss_channel' => array(
      'template' => 'theme/islandora-onthisday-rss-channel',
      'file' => 'theme/theme.inc',
      'variables' => array('islandora_objects' => NULL),
    ),
  );
}

/**
 * Implements hook_cron().
 */
function islandora_onthisday_cron() {
  module_load_include('inc', 'islandora_onthisday', 'includes/utilities');
  islandora_onthisday_clear_cache();
}

/**
 * Implements hook_block_info().
 */
function islandora_onthisday_block_info() {
  return array(
    'islandora_onthisday_random' => array(
      'visibility' => BLOCK_VISIBILITY_LISTED,
      'cache' => DRUPAL_NO_CACHE,
      'info' => t('Islandora On This Day'),
    ),
  );
}

/**
 * Implements hook_block_view().
 */
function islandora_onthisday_block_view($delta = '') {
  switch ($delta) {
    case 'islandora_onthisday_random':
      module_load_include('inc', 'islandora_onthisday', 'includes/utilities');
      if ($object = islandora_onthisday_get_random_object()) {
        $more_url = url("/onthisday");
        $more_markup = ' <span id="islandora-onthisday-random-more"><a href="' . $more_url . '">' . t('More...') . '</a></span>';
        $block['subject'] = t('On This Day') . $more_markup;
        $block['content'] = array(
          '#markup' => theme('islandora_onthisday_object',
            array('islandora_object' => $object)));
      }
      else {
        return FALSE;
      }
      break;
  }
  return $block;
}

/**
 * Menu callback.
 */
function islandora_onthisday_gallery($test_date = FALSE) {
  $today = date('F j');
  drupal_set_title("On this day, $today");
  module_load_include('inc', 'islandora_onthisday', 'includes/utilities');
  if (variable_get('islandora_onthisday_test_dates_enable', 0)) {
    $objects = islandora_onthisday_get_objects($test_date);
  }
  else {
    $objects = islandora_onthisday_get_objects();
  }
  $output = theme('islandora_onthisday_gallery', array('islandora_objects' => $objects));
  return $output;
}

/**
 * Menu callback.
 */
function islandora_onthisday_rss_channel() {
  module_load_include('inc', 'islandora_onthisday', 'includes/utilities');
  $objects = islandora_onthisday_get_objects();
  $output = theme('islandora_onthisday_rss_channel', array('islandora_objects' => $objects));
  return $output;
}

/**
 * Delivery callback.
 */
function islandora_onthisday_rss_output($rss_output) {
  drupal_add_http_header('Content-Type', 'application/rss+xml; charset=utf-8');
  print $rss_output;
}
