<?php

/**
 * @file
 * Module file.
 */

/**
 * Implements hook_menu().
 */
function islandora_onthisday_menu() {
  $items = array();
  $items['admin/islandora/tools/onthisday'] = array(
    'title' => 'Islandora On This Day',
    'description' => 'Configure the Islandora On This Day module.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('islandora_onthisday_admin_settings'),
    'access arguments' => array('administer site configuration'),
    'type' => MENU_NORMAL_ITEM,
  );
  return $items;
}

/**
 * Admin settings form builder.
 */
function islandora_onthisday_admin_settings() {
  $form['islandora_onthisday_date_fields'] = array(
    '#title' => t('Date fields in Solr to query'),
    '#type' => 'textfield',
    '#size' => 160,
    '#default_value' => variable_get('islandora_onthisday_date_fields', 'mods_originInfo_dateIssued_ms, mods_originInfo_dateCreated_ms'),
    '#description' => t("Comma-separated list of Solr field names to query for dates. Date will be in YYYY-MM-DD format."),
    '#maxlength' => 255,
  );
  return system_settings_form($form);
}
