<?php

/**
 * @file
 * Islandora-onthisday-rss-channel.tpl.php.
 *
 * Template for RSS channel for "on this day" items.
 */
?>
<?xml version="1.0"?>
<!-- RSS generated by <?php print $base_url; ?> on  <?php print date("F j, Y, g:i a e."); ?> -->
<rss version="2.0" xmlns:xhtml="http://www.w3.org/1999/xhtml">
<channel>
  <title><?php print $site_name; ?></title>
  <link><?php print $base_url; ?>/onthisday</link>
  <description>On this day, <?php print $today; ?></description>
  <language>en</language>
  <copyright />
  <managingEditor />
  <webMaster><?php print $site_mail; ?></webMaster>
<?php if (count($islandora_objects)): ?>
  <?php foreach($islandora_objects as $item): ?>
  <item>
  <?php if (strlen($item['year'])): ?>
    <title><?php print $item['label'] . ' [' . $item['year'] . ']'; ?></title>
  <?php else: ?>
    <title><?php print $item['label']; ?></title>
  <?php endif; ?>
    <link><?php print $item['url']; ?></link>
      <description><xhtml:img src="<?php print $item['thumb_link']; ?>" alt="Thumbnail image" /><xhtml:br /><?php print $item['description']; ?></description>
      <author />
      <guid isPermaLink="true"><?php print $item['url']; ?></guid>
      <pubDate />
      <category />
      <comments />
      <source url="<?php print $base_url; ?>"><?php print $site_name; ?></source>
      <enclosure url="<?php print $item['thumb_link']; ?>" length="<?php print $item['thumb_size']; ?>" type="<?php print $item['mimetype']; ?>" />
    </item>
  <?php endforeach; ?>
<?php endif; ?>
</channel>
</rss>
